/**
 * Engine smoke test: `pnpm --filter @elkdonis/astro test`.
 *
 * Planet golden values come from astrologychart2/sample_chart.json
 * (1990-05-15 14:30 America/New_York, New York City), generated by the
 * prototype on a machine whose local zone was US Eastern — the one setup where
 * its time-zone code gave the right answer — rounded to 2 dp.
 *
 * That file's HOUSES are wrong and must not be used as golden values: the
 * prototype called swe_houses(jd, flags, lat, lon, hsys), which the binding
 * reads as (jd, lat, lon, hsys), so every chart's houses were cast for
 * latitude 2° (SEFLG_SWIEPH), longitude 40.71°E. Houses here are instead
 * checked against an independent sidereal-time calculation.
 */

import assert from "node:assert/strict";
import { calculateChart, calculateSky, calculateSkyAt, timeZoneAt } from "../src/server";
import {
  chartToPoints,
  computeAspects,
  computeCrossAspects,
  formatPosition,
  localToUtc,
  stepInstant,
  synastryAspects,
  transitAspects,
} from "../src/index";
import { renderNatalSvg } from "../src/svg";
import { GLYPH_SCALE, renderWheelSvg } from "../src/wheel";

let passed = 0;
function check(name: string, fn: () => void) {
  fn();
  passed++;
  console.log(`  ✓ ${name}`);
}
const near = (actual: number, expected: number, tol: number, label: string) =>
  assert.ok(Math.abs(actual - expected) <= tol, `${label}: ${actual} not within ${tol} of ${expected}`);

console.log("time zones");
check("New York EDT 14:30 → 18:30Z", () => {
  assert.deepEqual(localToUtc("1990-05-15", "14:30", "America/New_York").utc, {
    year: 1990, month: 5, day: 15, hour: 18, minute: 30, second: 0,
  });
});
check("historical rule: New York in January is EST", () => {
  assert.equal(localToUtc("1990-01-15", "14:30", "America/New_York").offsetMinutes, -300);
});
check("fixed offset +05:30", () => {
  assert.equal(localToUtc("2000-01-01", "05:30", "+05:30").utc.hour, 0);
});
check("date rollover across midnight", () => {
  assert.deepEqual(localToUtc("2000-01-01", "01:00", "Asia/Tokyo").utc, {
    year: 1999, month: 12, day: 31, hour: 16, minute: 0, second: 0,
  });
});
check("spring-forward gap resolves forward (02:30 → 03:30 EDT)", () => {
  assert.equal(localToUtc("2021-03-14", "02:30", "America/New_York").utc.hour, 7);
});
check("fall-back overlap takes the earlier occurrence (EDT)", () => {
  assert.equal(localToUtc("2021-11-07", "01:30", "America/New_York").offsetMinutes, -240);
  assert.equal(localToUtc("2021-10-31", "01:30", "Europe/London").offsetMinutes, 60);
});
check("rejects impossible dates and unknown zones", () => {
  assert.throws(() => localToUtc("2023-02-30", "12:00", "UTC"));
  assert.throws(() => localToUtc("2023-01-01", "12:00", "Mars/Olympus_Mons"));
});
check("time zone from coordinates", () => {
  assert.equal(timeZoneAt(43.6532, -79.3832), "America/Toronto");
  assert.equal(timeZoneAt(51.5074, -0.1278), "Europe/London");
});

console.log("golden chart (sample_chart.json)");
const chart = calculateChart({
  date: "1990-05-15",
  time: "14:30",
  timezone: "America/New_York",
  latitude: 40.7128,
  longitude: -74.006,
  houseSystem: "P",
});
// [longitude from sample_chart.json, retrograde, house under the corrected cusps]
const golden: Record<string, [number, boolean, number]> = {
  sun: [54.66, false, 9],
  moon: [300.52, false, 5],
  mercury: [37.98, true, 8],
  venus: [13.13, false, 7],
  mars: [348.53, false, 6],
  jupiter: [99.59, false, 10],
  saturn: [295.24, true, 5],
  uranus: [279.18, true, 4],
  neptune: [284.35, true, 4],
  pluto: [226.16, true, 3],
};
check("utc", () => assert.equal(chart.utc, "1990-05-15T18:30:00.000Z"));
check("planet longitudes, retrogrades, houses", () => {
  // The golden table is the ten planets. Chiron and the Node are checked
  // separately, below — their reference values are not in sample_chart.json.
  for (const b of chart.bodies.filter((x) => golden[x.key])) {
    const [lon, retro, house] = golden[b.key];
    near(b.longitude, lon, 0.01, b.key);
    assert.equal(b.retrograde, retro, `${b.key} retrograde`);
    assert.equal(b.house, house, `${b.key} house`);
  }
});
check("angles agree with an independent sidereal-time calculation", () => {
  // IAU 1982 GMST, mean obliquity; good to a fraction of a degree, which is
  // all this needs to catch a swapped or mis-wired latitude/longitude.
  const rad = Math.PI / 180;
  const gmst = 280.46061837 + 360.98564736629 * (chart.julianDayUt - 2451545);
  const ramc = (((gmst + chart.input.longitude) % 360) + 360) % 360;
  const eps = 23.4393 * rad;
  const lat = chart.input.latitude * rad;
  const mc = (Math.atan2(Math.sin(ramc * rad), Math.cos(ramc * rad) * Math.cos(eps)) / rad + 360) % 360;
  const asc =
    (Math.atan2(Math.cos(ramc * rad), -(Math.sin(ramc * rad) * Math.cos(eps) + Math.tan(lat) * Math.sin(eps))) / rad +
      360) %
    360;
  near(chart.angles.midheaven, mc, 0.1, "MC");
  near(chart.angles.ascendant, asc, 0.1, "ASC");
  near(chart.houses[0].longitude, chart.angles.ascendant, 1e-9, "cusp 1 = ASC");
  near(chart.houses[9].longitude, chart.angles.midheaven, 1e-9, "cusp 10 = MC");
});
check("regression: not the prototype's lat-2°/lon-40.71° houses", () => {
  assert.ok(Math.abs(chart.angles.ascendant - 279.73) > 1, "ASC matches the buggy prototype value");
});
check("summary", () => {
  assert.equal(chart.summary.sun, "taurus");
  assert.equal(chart.summary.moon, "aquarius");
  assert.equal(chart.summary.rising, "virgo");
});
check("aspects: Uranus–Neptune conjunction found, majors sorted first", () => {
  const urNep = chart.aspects.find((a) => a.a === "uranus" && a.b === "neptune");
  assert.ok(urNep, "Uranus–Neptune present");
  assert.equal(urNep.type, "conjunction");
  near(urNep.orb, 5.17, 0.02, "orb");
  assert.ok(
    !chart.aspects.some((a) => a.a === "saturn" && a.b === "neptune" && a.type === "conjunction"),
    "Saturn–Neptune at 10.9° is outside the 8° orb",
  );
  assert.ok(chart.aspects.every((a, i, all) => i === 0 || Number(all[i - 1].major) >= Number(a.major)));
});
check("aspects to the angles: listed with the angle second, tighter orbs, never angle–angle", () => {
  const toAngles = chart.aspects.filter((a) => a.b === "ascendant" || a.b === "midheaven");
  assert.ok(toAngles.length > 0, "the reference chart has planets aspecting AC/MC");
  assert.ok(chart.aspects.every((a) => a.a !== "ascendant" && a.a !== "midheaven"), "angles are never `a`");
  assert.ok(toAngles.every((a) => a.orb <= 6), "angle orbs are three quarters of the planetary orbs (≤ 6°)");
  const keys = chart.aspects.map((a) => `${a.a}-${a.b}-${a.type}`);
  assert.equal(new Set(keys).size, keys.length, "no duplicate aspects");
});
check("formatting", () => {
  assert.equal(formatPosition(54.66), "24° Taurus 40′");
  assert.equal(formatPosition(29.9999), "0° Taurus 00′");
});

console.log("stepping through time");
check("hour, day and week steps, in any amount", () => {
  const t = new Date("2026-09-11T21:00:00Z");
  assert.equal(stepInstant(t, "hour", 1).toISOString(), "2026-09-11T22:00:00.000Z");
  assert.equal(stepInstant(t, "hour", 6).toISOString(), "2026-09-12T03:00:00.000Z");
  assert.equal(stepInstant(t, "day", -1).toISOString(), "2026-09-10T21:00:00.000Z");
  assert.equal(stepInstant(t, "week", 1).toISOString(), "2026-09-18T21:00:00.000Z");
  assert.equal(stepInstant(t, "month", -3).toISOString(), "2026-06-11T21:00:00.000Z");
});
check("year steps keep the date, clamping 29 February", () => {
  assert.equal(stepInstant(new Date("2026-09-11T21:00:00Z"), "year", 1).toISOString(), "2027-09-11T21:00:00.000Z");
  assert.equal(stepInstant(new Date("2024-02-29T12:00:00Z"), "year", 1).toISOString(), "2025-02-28T12:00:00.000Z");
  assert.equal(stepInstant(new Date("2024-02-29T12:00:00Z"), "year", -1).toISOString(), "2023-02-28T12:00:00.000Z");
});
check("month steps keep the day, clamped to the month's length", () => {
  const jan31 = new Date("2026-01-31T12:00:00Z");
  assert.equal(stepInstant(jan31, "month", 1).toISOString(), "2026-02-28T12:00:00.000Z");
  assert.equal(stepInstant(new Date("2024-01-31T12:00:00Z"), "month", 1).toISOString(), "2024-02-29T12:00:00.000Z");
  assert.equal(stepInstant(new Date("2026-03-31T12:00:00Z"), "month", -1).toISOString(), "2026-02-28T12:00:00.000Z");
  assert.equal(stepInstant(new Date("2026-01-15T12:00:00Z"), "month", -1).toISOString(), "2025-12-15T12:00:00.000Z");
});
check("a day of stepping moves the Moon about 13°", () => {
  const t = new Date("2026-09-11T12:00:00Z");
  const a = calculateSkyAt(t);
  const b = calculateSkyAt(stepInstant(t, "day", 1));
  const moved = ((b.bodies[1].longitude - a.bodies[1].longitude + 540) % 360) - 180;
  assert.ok(moved > 11 && moved < 16, `Moon moved ${moved}° in a day`);
});

console.log("other");
check("sky now computes", () => {
  const sky = calculateSky();
  assert.equal(sky.bodies.length, 12);
  assert.equal(sky.houses.length, 12);
});
check("ephemeris data files are found and used", () => {
  // Not fatal when absent (Moshier is a valid fallback), but say so loudly.
  if (chart.ephemeris !== "swiss") {
    console.log("    ! no .se1 files resolved — running on Moshier");
  }
});
check("polar latitude Placidus warns instead of failing", () => {
  const polar = calculateChart({ date: "2000-06-21", time: "12:00", timezone: "UTC", latitude: 78.2, longitude: 15.6 });
  assert.equal(polar.houses.length, 12);
  assert.ok(polar.warnings.length > 0);
});
check("SVG renderer produces a self-contained drawing", () => {
  const svg = renderNatalSvg(chart, { name: "Reference chart", locationName: "New York City" });
  assert.ok(svg.startsWith("<svg") && svg.trimEnd().endsWith("</svg>"));
  assert.ok(!/<text|font-family|@font-face/.test(svg), "all type must be outlines");
  // opentype.js 1.3.5 emitted NaN coordinates in some outlines, which makes a
  // browser abandon the rest of that path — the package pins 1.3.4.
  assert.ok(!svg.includes("NaN"), "no NaN coordinates in path data");
  assert.ok(svg.includes("Reference chart") === false, "name is rendered as paths, not text");
  assert.ok((svg.match(/<line /g) ?? []).length > 300, "ticks, cusps, radials and aspects drawn");
});
check("client wheel renders small, with text and no NaN; compact is tighter", () => {
  const full = renderWheelSvg(chart);
  const compact = renderWheelSvg(chart, { variant: "compact" });
  assert.ok(full.startsWith("<svg") && full.includes("<text"), "wheel uses <text>");
  assert.ok(!full.includes("NaN") && !compact.includes("NaN"));
  assert.ok(full.length < 90_000, `wheel is ${full.length} bytes — should stay small`);
  assert.ok(compact.includes('viewBox="0 0 680 680"') && full.includes('viewBox="0 0 1180 1180"'));
  assert.ok(!compact.includes("SAGITTARIUS") && full.includes("SAGITTARIUS"), "compact drops sign names");
  assert.ok(!full.includes("PLANETS"), "wheel layout has no tables");
});
check("bad input throws ChartInputError", () => {
  assert.throws(
    () => calculateChart({ date: "1990-05-15", time: "14:30", timezone: "UTC", latitude: 95, longitude: 0 }),
    { name: "ChartInputError" },
  );
});

console.log("Chiron and the North Node");
check("the reference chart's points land in the right signs", () => {
  // Degrees from our own engine would only prove it agrees with itself. The
  // SIGN is independently checkable against any published ephemeris: the
  // nodal axis sat in Aquarius/Leo from late 1989 to mid 1991, and Chiron
  // was in Cancer from 1988 to 1991.
  const node = chart.bodies.find((b) => b.key === "northNode")!;
  const chiron = chart.bodies.find((b) => b.key === "chiron")!;
  assert.equal(node.sign, "aquarius", "North Node in Aquarius on 1990-05-15");
  assert.equal(chiron.sign, "cancer", "Chiron in Cancer on 1990-05-15");
});

check("both points are computed, after the ten planets", () => {
  assert.equal(chart.bodies.length, 12);
  // Appended, never inserted: plenty of callers read bodies[0]/[1] as the
  // Sun and Moon.
  assert.equal(chart.bodies[0].key, "sun");
  assert.equal(chart.bodies[1].key, "moon");
  const node = chart.bodies.find((b) => b.key === "northNode");
  const chiron = chart.bodies.find((b) => b.key === "chiron");
  assert.ok(node && chiron, "both points present");
  assert.ok(node.retrograde, "the lunar node travels backwards");
  assert.ok(node.house >= 1 && node.house <= 12 && chiron.house >= 1 && chiron.house <= 12);
});

check("the element balance still counts ten planets, not twelve bodies", () => {
  const total = Object.values(chart.summary.elements).reduce((a, b) => a + b, 0);
  assert.equal(total, 10, "adding points must not shift every chart's balance");
  assert.equal(Object.values(chart.summary.modalities).reduce((a, b) => a + b, 0), 10);
});

check("points are held to half the planetary orb", () => {
  // Sun and Chiron 5° apart: inside the 8° conjunction orb for two planets,
  // outside the 4° a point is allowed.
  const wide = computeAspects([
    { key: "sun", longitude: 100, speed: 1 },
    { key: "mars", longitude: 105, speed: 0.5 },
  ]);
  const tight = computeAspects([
    { key: "sun", longitude: 100, speed: 1 },
    { key: "chiron", longitude: 105, speed: 0.05 },
  ]);
  assert.equal(wide.length, 1, "5° is a planetary conjunction");
  assert.equal(tight.length, 0, "5° is outside a point's half orb");
});

check("a chart before Chiron's ephemeris keeps its planets and says so", () => {
  const old = calculateChart({ date: "0400-03-01", time: "12:00", timezone: "UTC", latitude: 41.9, longitude: 12.5 });
  assert.ok(!old.bodies.some((b) => b.key === "chiron"), "Chiron is dropped, not faked");
  assert.ok(old.bodies.length >= 10, "every planet still computed");
  assert.ok(old.warnings.some((w) => w.includes("Chiron")), "and the chart says why");
});

check("every body has a client glyph size — a missing one silently mis-scales", () => {
  const svg = renderWheelSvg(chart);
  for (const key of ["northNode", "chiron"]) {
    assert.ok(GLYPH_SCALE[key], `${key} needs a measured entry in GLYPH_SCALE`);
  }
  assert.ok(svg.includes("\u260A") || svg.includes("☊"), "the node is drawn");
  assert.ok(svg.includes("\u26B7") || svg.includes("⚷"), "Chiron is drawn");
});

console.log("transits (bi-wheel)");
{
  // A moment far from the reference chart, so the contacts are incidental
  // rather than a return of anything.
  const transit = calculateSkyAt(new Date("2026-09-12T19:00:00Z"), 40.7128, -74.006);

  check("transit orbs are much tighter than natal ones", () => {
    // Same pair of point lists through both engines: the natal orb table is
    // 6-8° on the majors, the transit table 3°, so transits must find fewer.
    const natalWide = computeAspects([...chartToPoints(transit, { angles: false }), ...chartToPoints(chart)]);
    const cross = transitAspects(chart, transit);
    assert.ok(cross.length > 0, "some transit contacts exist");
    assert.ok(
      cross.every((a) => a.orb <= 3),
      `every major transit is within 3°, widest was ${Math.max(...cross.map((a) => a.orb)).toFixed(2)}`,
    );
    assert.ok(natalWide.length > cross.length, "natal orbs admit more pairs than transit orbs");
  });

  check("cross aspects are a full product, not the upper triangle", () => {
    const cross = computeCrossAspects(chartToPoints(transit, { angles: false }), chartToPoints(chart));
    // Same-body pairs (transiting Sun to natal Sun) are exactly what a
    // one-chart pass skips, and exactly what a return is.
    const sunToSun = computeCrossAspects(
      [{ key: "sun", longitude: 100, speed: 1 }],
      [{ key: "sun", longitude: 100, speed: 0 }],
    );
    assert.equal(sunToSun.length, 1, "a solar return is a conjunction of Sun to Sun");
    assert.equal(sunToSun[0].type, "conjunction");
    assert.ok(cross.every((a) => a.moving !== undefined && a.fixed !== undefined));
  });

  check("applying/separating follows the transiting body alone", () => {
    // Natal point at 100°, transit at 97° and closing: applying. The natal
    // side carries a speed that must be ignored.
    const closing = computeCrossAspects(
      [{ key: "mars", longitude: 97, speed: +0.5 }],
      [{ key: "venus", longitude: 100, speed: +99 }],
    );
    assert.equal(closing[0].applying, true, "a transit moving toward exact is applying");
    const retro = computeCrossAspects(
      [{ key: "mars", longitude: 97, speed: -0.5 }],
      [{ key: "venus", longitude: 100, speed: +99 }],
    );
    assert.equal(retro[0].applying, false, "retrograde away from exact is separating");
  });

  check("the Moon gets half the orb, because degrees are really hours", () => {
    const moon = computeCrossAspects(
      [{ key: "moon", longitude: 98, speed: 13 }],
      [{ key: "sun", longitude: 100, speed: 0 }],
    );
    const mars = computeCrossAspects(
      [{ key: "mars", longitude: 98, speed: 0.5 }],
      [{ key: "sun", longitude: 100, speed: 0 }],
    );
    assert.equal(mars.length, 1, "2° conjunction is inside Mars's 3° orb");
    assert.equal(moon.length, 0, "2° is outside the Moon's 1.5° orb");
  });

  check("bi-wheel draws two rings and only the cross aspects", () => {
    const bi = renderWheelSvg(chart, { transits: transit });
    const plain = renderWheelSvg(chart);
    assert.ok(!bi.includes("NaN"), "no NaN coordinates");
    assert.ok(bi.length < 90_000, `bi-wheel is ${bi.length} bytes — should stay small`);
    // The transiting ring is inked differently so the two charts are told
    // apart; the natal wheel never uses that colour.
    assert.ok(bi.includes("#4a3f7a"), "transit ring has its own ink");
    assert.ok(!plain.includes("#4a3f7a"), "a plain wheel has no transit ink");
    // Two rings of ten bodies, at the two lane radii.
    const atRadius = (svg: string, r: number) => {
      const hits = [...svg.matchAll(/<text[^>]*x="([-\d.]+)"[^>]*y="([-\d.]+)"/g)].filter((m) => {
        const d = Math.hypot(Number(m[1]) - 590, Number(m[2]) - 590);
        return Math.abs(d - r) < 6;
      });
      return hits.length;
    };
    assert.ok(atRadius(bi, 364) >= 8, "a ring of transiting glyphs sits at R_T");
    assert.ok(atRadius(bi, 258) >= 8, "the natal ring moves in to R_P");
    // A plain wheel keeps the natal planets in the wider lane and has no
    // second ring at all. (Radii alone can't say "nothing is at 364" — a
    // one-chart wheel puts its house numbers near there.)
    assert.ok(atRadius(plain, 296) >= 8, "a plain wheel keeps its planets at the roomier R_P");
    assert.ok(atRadius(plain, 258) === 0, "and nothing in the bi-wheel's tightened lane");
  });

  check("synastry: wider orbs than transits, tighter than natal, both sets of angles", () => {
    const other = calculateChart({
      date: "1988-11-02", time: "09:15", timezone: "America/Toronto",
      latitude: 43.6532, longitude: -79.3832,
    });
    const syn = synastryAspects(chart, other);
    const tra = transitAspects(chart, other);
    assert.ok(syn.length > 0, "two charts have interaspects");
    assert.ok(syn.every((a) => a.orb <= 5), "majors within 5°");
    assert.ok(syn.length >= tra.length, "5° admits at least as much as 3°");
    // Transits drop the moving chart's angles; synastry keeps both sides'.
    assert.ok(
      syn.some((a) => a.moving === "ascendant" || a.moving === "midheaven"),
      "the outer chart's angles take part in synastry",
    );
    assert.ok(
      !tra.some((a) => a.moving === "ascendant" || a.moving === "midheaven"),
      "a transiting Ascendant is not a transit",
    );
  });

  check("synastry has no applying — neither chart moves", () => {
    const other = calculateChart({
      date: "1988-11-02", time: "09:15", timezone: "America/Toronto",
      latitude: 43.6532, longitude: -79.3832,
    });
    assert.ok(
      synastryAspects(chart, other).every((a) => a.applying === false),
      "speeds are zeroed, so nothing reads as applying",
    );
  });

  check("a bi-wheel's chart is unchanged — transits are a view, not a mutation", () => {
    const before = JSON.stringify(chart);
    renderWheelSvg(chart, { transits: transit });
    assert.equal(JSON.stringify(chart), before);
  });
}

console.log(`\n${passed} checks passed (ephemeris: ${chart.ephemeris})`);
