// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/artists" | "/commitments" | "/complete" | "/edit/[slug]" | "/hub" | "/login" | "/signup/setup" | "/sites/[slug]" | "/wizard" | "/wizard/business" | "/wizard/confirm"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/auth/session" | "/api/auth/signup" | "/api/org/create" | "/api/org/join" | "/api/silex/auth" | "/api/silex/publish" | "/api/silex/token" | "/api/wizard/business/save" | "/api/wizard/business/submit" | "/api/wizard/save" | "/api/wizard/submit"
type PageRoutes = never
type LayoutRoutes = "/" | "/wizard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/session": {}
  "/api/auth/signup": {}
  "/api/org/create": {}
  "/api/org/join": {}
  "/api/silex/auth": {}
  "/api/silex/publish": {}
  "/api/silex/token": {}
  "/api/wizard/business/save": {}
  "/api/wizard/business/submit": {}
  "/api/wizard/save": {}
  "/api/wizard/submit": {}
  "/artists": {}
  "/commitments": {}
  "/complete": {}
  "/edit/[slug]": { "slug": string; }
  "/hub": {}
  "/login": {}
  "/signup/setup": {}
  "/sites/[slug]": { "slug": string; }
  "/wizard": {}
  "/wizard/business": {}
  "/wizard/confirm": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/wizard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
